services:
- type: web
  name: mtglist-price-proxy
  env: ruby
  buildCommand: |
    apt-get update && apt-get install -y chromium
    bundle install
  startCommand: bundle exec rackup config.ru -o 0.0.0.0 -p $PORT
  envVars:
    - key: RACK_ENV
      value: production
    - key: DEBUG_MODE
      value: "false"
    - key: RUBY_VERSION
      value: "3.4.3"
  plan: free 