services:
- type: web
  name: mtglist-price-proxy
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeploy: true
  branch: main
  envVars:
    - key: RACK_ENV
      value: production
    - key: DEBUG_MODE
      value: "false"
    - key: PORT
      value: "10000"
    - key: DISPLAY
      value: ":99"
    - key: TESSDATA_PREFIX
      value: "/usr/share/tesseract-ocr/4.00/tessdata"
  plan: free
  healthCheckPath: /
  numInstances: 1 