services:
- type: web
  name: mtglist-price-proxy
  env: docker
  dockerfilePath: ./Dockerfile
  envVars:
    - key: RACK_ENV
      value: production
    - key: DEBUG_MODE
      value: "false"
    - key: PORT
      value: "10000"
  plan: free 