services:
- type: web
  name: mtglist-price-proxy
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeploy: true
  branch: main
  startCommand: bundle exec rackup config.ru -o 0.0.0.0 -p 10000
  envVars:
    - key: RACK_ENV
      value: production
    - key: DEBUG_MODE
      value: "false"
    - key: PORT
      value: "10000"
  plan: free
  healthCheckPath: /
  numInstances: 1 